name: c_color
description: s
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+7
  path_provider: ^2.0.8
  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

