name: c_color
description: s
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+7
  path_provider: ^2.0.8
  image: ^3.0.1
  tflite: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

assets:
  - assets/ssd_mobilenet.tflite
  - assets/ssd_mobilenet.txt

